services:
  app:
    container_name: inspection-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    volumes:
      - /app/node_modules  # Hanya node_modules yang perlu dipertahankan
    command: ["npm", "start"]
